stages:
  - Documentation

Report:
  image: fridezlucas/awesome-doc
  stage: Documentation
  script:
    - chmod +x ./doc/generatedocs.sh ./doc/generateuml.sh
    - ./doc/generateuml.sh
    - ./doc/generatedocs.sh
  artifacts:
    paths:
      - "*.pdf"
    expire_in: 1 week
